### ISSUE TITLE
Upload to conda-forge

### ISSUE THREAD

**Issue by nmichale** [neo4j-drivers/neo4j-python-driver-rust-ext#31]
It would be great if this was also available via conda. [The original python](https://anaconda.org/conda-forge/neo4j-python-driver) driver is setup that way.

**Comment by robsdedude** [comment]
Thank you for the suggestion. It's somewhat involved, but I'll see how far I can get :)

https://github.com/conda-forge/staged-recipes/pull/28146

**Comment by robsdedude** [comment]
5.26.0.0 is now available on conda forge :tada: 

https://anaconda.org/conda-forge/neo4j-python-driver-rust-ext

**Comment by nmichale** [comment]
> 5.26.0.0 is now available on conda forge 🎉
> 
> https://anaconda.org/conda-forge/neo4j-python-driver-rust-ext

Thanks so much!
